### ISSUE TITLE
SFSQL 1.1 Compliance Test Suite - Types and Functions T40, T49 and T50 queries do not return expected result.

### ISSUE THREAD

**Issue by telmessos** [opengeospatial/ets-sfs11#1]
I created a database using the schemas given (Replaced some parts of them with PostGIS versions.)

I executed the queries one by one. Most of them works fine. But T40 does not return the expected result. 

And queries T49 and T50 which are st_union and SymmetricDifference functions returns requested result plus the geometries of the selected two objects. 

Please see the database schema follows https://gist.github.com/telmessos/5f194c7d9c9cf49c256f

**Comment by telmessos** [comment]
It seems to be a problem about the difference between OpenGIS Within function and PostGIS ST_Within function.

OpenGIS Within Function
Within(A:B):Integer — Returns 1 (TRUE) if this B is ‘spatially within’ A.

PostGIS ST_Within Function
boolean ST_Within(geometry A, geometry B); Returns true if the geometry A is completely inside geometry B

So the order of the geometry must be opposite in these two functions.

@bermud if it is ok for you I'll close the question.

**Comment by bermud** [comment]
I'm happy you found the explanation of problem. I'll close the issue.
