### ISSUE TITLE
Update CTL with better information about conformance classes 

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sfs11#2]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by keshavnangare** [comment]
@dstenger 

According to documentation: http://opengeospatial.github.io/ets-sfs11/

Three conformance classes are described in the testing guidance document (see OGC 98-046r2):

- SQL 92 Implementation of Feature Tables, Normalized Geometry Schema - SFS (NG)
- SQL 92 Implementation of Feature Tables, Binary Geometry Schema - SFS (BG)
- SQL 92 with Geometry Types and Functions Implementation of Feature Tables - SFS (TF)


But the above conformance class inplemenation is not found in test. 
https://github.com/opengeospatial/ets-sfs11/blob/master/src/main/scripts/ctl/sfs-suite.xml

The same issue is with the ets-sfs12. https://github.com/opengeospatial/ets-sfs12/issues/1

Can you please take look?

**Comment by dstenger** [comment]
No actual tests are implemented and just a file upload is existing.

Thus, basic conformance classes cannot be configured.
